name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/deploy-vps-project
            sudo git pull origin main

            sudo docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
            sudo docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true

            sudo docker build -t reactjs-vps-image .
            sudo docker run -d --restart=always \
              -p 80:80 -p 443:443 \
              -v /etc/letsencrypt:/etc/letsencrypt:ro \
              --name ${{ secrets.DOCKER_CONTAINER_NAME }} reactjs-vps-image
