name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/deploy-vps-project
          git pull origin main

          docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} || true
          docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} || true

          docker build -t reactjs-vps-image .
          docker run -d --restart=always \
            -p 80:80 -p 443:443 \
            -v /etc/letsencrypt:/etc/letsencrypt:ro \
            --name ${{ secrets.DOCKER_CONTAINER_NAME }} reactjs-vps-image
